Vagrant.require_version ">= 2.0.0"
Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
    vb.cpus = 1
  end
  config.vm.provision "shell", path: "install.sh", privileged: true

end
